postgres:
  user: "postgres"
  password: "postgres"
  host: "postgres_db_cw"
  port: 5432
  dbname: "fift"

minio:
  endpoint: "miniocw:9000"
  access_key: "ift_bigdata"
  secret_key: "minio_password"
  bucket_name: "portfolio"
  secure: false

yf_pipeline:
  batch_size: 50
  fetch_years: 10
  fx_list: ["EURUSD=X", "GBPUSD=X", "USDJPY=X", "USDCHF=X", "USDCAD=X", "AUDUSD=X", "NZDUSD=X"]
  invert_fx_list: ["USDJPY=X", "USDCHF=X", "USDCAD=X"]
  extra_tickers: ["ACWI", "URTH", "XLP", "^892400-USD-STRD", "^990100-USD-STRD", "^704853-USD-STRD"]