postgres:
  user: "postgres"
  password: "postgres"
  host: "postgres_db_cw"
  port: 5432
  dbname: "fift"

minio:
  endpoint: "miniocw:9000"
  access_key: "ift_bigdata"
  secret_key: "minio_password"
  secure: false
  bucket_name: "portfolio"

mongodb:
  host: "mongo_db"
  port: "27017"
  dbname: "trading_db"
  collection: "trade_logs"

portfolio:
  sectors: ["Consumer Staples", "Utilities", "Health Care"]
  momentum_weight: 0.35
  fey_weight: 0.25
  trend_weight: 0.2
  risk_weight: 0.15
  liquidity_weight: 0.05
  health_sector_cap: 0.3
  stock_cap: 0.1
  benchmark_symbol: "^990100-USD-STRD"

trading:
  transaction_fee: 0.001
  initial_capital: 1000000