postgresql:
  host: localhost
  port: 5439
  user: postgres
  password: postgres
  database: fift

mongodb:
  host: localhost
  port: 27019
  database: wald_db

minio:
  endpoint: localhost:9000
  access_key: ift_bigdata
  secret_key: minio_password
  secure: false
  bucket: csreport
